### ISSUE TITLE
Rezept - Portionen

### ISSUE THREAD

**Issue by LiFaytheGoblin** [AllNasiGoreng/AllNasiGoreng.github.io#11]
Klären wieviele Portionen das sind,
hinschreiben

**Comment by GunBlade92** [comment]
Portionen schon angegeben

**Comment by LiFaytheGoblin** [comment]
@GunBlade92 
Super Icon! Aber wegen der Position: Würdest du es nicht vielleicht eher bei Zutaten erwarten? Ich glaube, da wäre es besser! Einfach rechts daneben oder so? Vielleicht nicht am rechten Rand, weil in mobil musst du mal schauen, sieht das irgendwie komisch aus...
