### ISSUE TITLE
Validieren & Ende

### ISSUE THREAD

**Issue by LiFaytheGoblin** [AllNasiGoreng/AllNasiGoreng.github.io#15]
Finishing

**Comment by LiFaytheGoblin** [comment]
CSS auf Dopplungen prüfen!
Validieren! https://jigsaw.w3.org/css-validator/

**Comment by GunBlade92** [comment]
@LiFaytheGoblin 
Validiert. https://jigsaw.w3.org/css-validator/validator?uri=allnasigoreng.github.io&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en

**Comment by LiFaytheGoblin** [comment]
@GunBlade92 
Nice! Ich würde sagen jetzt müssen wir nurnoch nochmal den Code anschauen, 
- schauen ob alles geordnet ist, 
- alle duplikate/redundanten code entfernen
