### ISSUE TITLE
Rezept - Veggie Kennzeichnung

### ISSUE THREAD

**Issue by LiFaytheGoblin** [AllNasiGoreng/AllNasiGoreng.github.io#35]
Ich finde, die Icons zur Fleisch/Veggie Kennzeichnung sehen etwas zu groß aus - könnte man die kleiner machen, und vielleicht auch nicht neben Zutaten, sondern neben den Titel des Rezeptes setzen?

**Comment by GunBlade92** [comment]
icons schon verändert

**Comment by LiFaytheGoblin** [comment]
Sieht gut aus!
