### ISSUE TITLE
Footer - Padding, List

### ISSUE THREAD

**Issue by LiFaytheGoblin** [AllNasiGoreng/AllNasiGoreng.github.io#36]
Der Footer braucht mehr Padding (auch oben und unten). Er sieht noch etwas gequetscht aus.
Es wäre auch gut wenn die Liste weiter links wäre, also nicht so weit eingerückt, weil das sonst bei kleinem Bildschirm komisch aussieht.

**Comment by GunBlade92** [comment]
Padding schon verändert

**Comment by LiFaytheGoblin** [comment]
@GunBlade92 
Was ist mit der Liste? 
weil momentan ist das bei mobil so:
![listefooter](https://cloud.githubusercontent.com/assets/5471273/15822470/3e819776-2bf6-11e6-961f-d2b2f7923e07.PNG)

**Comment by GunBlade92** [comment]
Ich verstehe nicht, was du meinst. Ist der Liste zu weit nach rechts?
