### ISSUE TITLE
Feedback - Mobil?

### ISSUE THREAD

**Issue by LiFaytheGoblin** [AllNasiGoreng/AllNasiGoreng.github.io#37]
Prüfen, ob Feedback für Mobil okay ist (kann man gut Text eingeben oder sind die Felder zu klein?

**Comment by GunBlade92** [comment]
Feedback für Mobil schon geprüft. Textfelder nicht zu klein, aber der Text ist zu klein, auch fur die Vor- und Nachname Input. Deswegen, habe ich den Textgroße verändert. Ich habe auch der Font für <legend> und <label> nach Originalform zurückgesetzt.

**Comment by LiFaytheGoblin** [comment]
@GunBlade92 
Okay gut.
Was ist mit dem Textfeld am Ende? Ich habe das Gefühl, dass es manchmal abgeschnitten wird?
