### ISSUE TITLE
Aller Text ist auf einmal rechtszentriert!

### ISSUE THREAD

**Issue by LiFaytheGoblin** [AllNasiGoreng/AllNasiGoreng.github.io#38]
Hervorgerufen durch 

```
p{
        text-align: right;
    }
```

eingefügt am 5.6.2016

Wozu ist das und könntest du das anders machen, sodass nicht alles rechts zentriert ist? Evtl mit einem anderen Selector?

**Comment by GunBlade92** [comment]
@LiFaytheGoblin 
Bug schon gefixt. Der p element ist eigentlich für der Wort "Portion". Ich möchte der Wort nach rechts ziehen. Ich habe gedacht, dass diese Element noch nicht genutzt, weil ich habe diese Element in der ganze Webseite nicht gesehen. Ich habe mit anderen Selector benutzt, diese Wort zuziehen.
