### ISSUE TITLE
Feedback - Legend - CSS Validierungs Fehler

### ISSUE THREAD

**Issue by LiFaytheGoblin** [AllNasiGoreng/AllNasiGoreng.github.io#40]
![css error](https://cloud.githubusercontent.com/assets/5471273/15823540/5e40269a-2bfb-11e6-89ff-f6c0f14fd840.PNG)

**Comment by GunBlade92** [comment]
Ich habe der Legend element in der CSS entfernt. Eigentlich möchte ich der Text mit dem <legend> Element bold machen, aber sieht es nicht gut aus. Deswegen habe ich das entfernt.
